export const MEMORY_BOOK_MIN_ASSIGNED_MEMORIES = 6
export const MEMORY_BOOK_MAX_PAGES = 10
export const MEMORY_BOOK_PHOTOS_PER_PAGE = 2
export const MEMORY_BOOK_MAX_ASSIGNED_MEMORIES =
  MEMORY_BOOK_MAX_PAGES * MEMORY_BOOK_PHOTOS_PER_PAGE