begin;

-- Device uploads already live inside private, book-owned R2 storage. Their
-- 320px/640px previews are therefore generated by the book asset pipeline,
-- not by the shared My Media derivative pipeline.
with upload_derivatives as (
  select id
  from public.memory_book_media_derivatives
  where source_type = 'upload'
)
update public.memory_book_jobs j
set
  status = 'completed',
  result = jsonb_build_object('superseded', true),
  completed_at = timezone('utc', now()),
  lease_expires_at = null,
  locked_by = null
where j.job_type = 'generate_media_derivatives'
  and j.status in ('queued', 'failed', 'dead')
  and j.payload->>'derivativeId' in (select id::text from upload_derivatives);

delete from public.memory_book_media_derivatives
where source_type = 'upload';

-- Repair uploads that were preserved successfully but left pending because
-- no worker generated their optimized book previews.
update public.memory_book_assets
set
  preserved_key = coalesce(preserved_key, source_locator),
  status = case
    when metadata ? 'thumbnailSmallKey' and metadata ? 'thumbnailMediumKey'
      then 'ready'
    else 'pending'
  end,
  metadata = metadata || jsonb_build_object(
    'preservationStatus', 'ready',
    'previewStatus', case
      when metadata ? 'thumbnailSmallKey' and metadata ? 'thumbnailMediumKey'
        then 'ready'
      else 'queued'
    end
  ),
  error_message = null
where source_type = 'upload'
  and media_type = 'image'
  and coalesce(preserved_key, source_locator) is not null;

update public.memory_book_jobs j
set
  status = 'completed',
  result = jsonb_build_object('superseded', true),
  completed_at = timezone('utc', now()),
  lease_expires_at = null,
  locked_by = null
from public.memory_book_assets a
where j.asset_id = a.id
  and a.source_type = 'upload'
  and j.job_type = 'preserve_asset'
  and j.status in ('queued', 'failed', 'dead')
  and j.idempotency_key not like 'upload-preview-v2:%';

insert into public.memory_book_jobs (
  user_id,
  book_id,
  asset_id,
  job_type,
  idempotency_key,
  payload
)
select
  a.user_id,
  a.book_id,
  a.id,
  'preserve_asset',
  'upload-preview-v2:' || a.id || ':' || coalesce(a.preserved_key, a.source_locator),
  jsonb_build_object('previewOnly', true)
from public.memory_book_assets a
where a.source_type = 'upload'
  and a.media_type = 'image'
  and coalesce(a.preserved_key, a.source_locator) is not null
  and not (a.metadata ? 'thumbnailSmallKey' and a.metadata ? 'thumbnailMediumKey')
on conflict (idempotency_key) do nothing;

commit;
