export type ThemeCategory =
  | "All"
  | "Studio"
  | "Formal"
  | "Cozy"
  | "Outdoor"
  | "Lifestyle"
  | "Retro"
  | "Holiday"
  | "Royal"
  | "Fine Art"

export type ClothingMode = "preserve" | "restyle"

export interface FamilyPortraitTheme {
  id: string
  name: string
  category: ThemeCategory
  description: string
  badge?: string
  previewColor: string
  defaultClothingMode: ClothingMode
  // Prompt components
  environment: string
  outfit: string
  lighting: string
  compositionHint: string
}

export const FAMILY_PORTRAIT_THEMES: FamilyPortraitTheme[] = [
  // ── Original Studio Backgrounds (proven high face-match) ──────────────
  {
    id: "studio-matte-black",
    name: "Matte Black",
    category: "Studio",
    description: "Classic matte charcoal seamless backdrop with soft falloff — your proven studio favourite.",
    badge: "Proven",
    previewColor: "from-gray-950 via-gray-900 to-black",
    defaultClothingMode: "preserve",
    environment: "a matte charcoal seamless backdrop with soft falloff to near-black background.",
    outfit: "",
    lighting: "unified, professional studio lighting (e.g., softbox) consistently across all subjects.",
    compositionHint: "",
  },
  {
    id: "studio-neutral-gray",
    name: "Neutral Gray",
    category: "Studio",
    description: "Even-toned mid-gray seamless paper with slight vignette.",
    previewColor: "from-gray-700 via-gray-600 to-gray-800",
    defaultClothingMode: "preserve",
    environment: "a neutral mid-gray seamless paper; evenly lit; slight vignette background.",
    outfit: "",
    lighting: "unified, professional studio lighting (e.g., softbox) consistently across all subjects.",
    compositionHint: "",
  },
  {
    id: "studio-warm-beige",
    name: "Warm Beige",
    category: "Studio",
    description: "Light warm beige high-key look with soft shadows.",
    previewColor: "from-amber-200 via-orange-100 to-yellow-100",
    defaultClothingMode: "preserve",
    environment: "a light warm beige background; high-key look; soft shadows only.",
    outfit: "",
    lighting: "unified, professional studio lighting (e.g., softbox) consistently across all subjects.",
    compositionHint: "",
  },
  {
    id: "studio-gradient",
    name: "Subtle Gradient",
    category: "Studio",
    description: "Faint center-weighted gradient from dark to light.",
    previewColor: "from-slate-800 via-slate-500 to-slate-300",
    defaultClothingMode: "preserve",
    environment: "a very faint center-weighted gradient from dark to light; avoid banding background.",
    outfit: "",
    lighting: "unified, professional studio lighting (e.g., softbox) consistently across all subjects.",
    compositionHint: "",
  },
  {
    id: "studio-dark-brown",
    name: "Dark Brown Vignette",
    category: "Studio",
    description: "Classic dark brown background with a gentle vignette.",
    badge: "Original",
    previewColor: "from-amber-950 via-yellow-950 to-stone-950",
    defaultClothingMode: "preserve",
    environment: "a classic dark brown background with a gentle vignette.",
    outfit: "",
    lighting: "unified, professional studio lighting (e.g., softbox) consistently across all subjects.",
    compositionHint: "",
  },
  {
    id: "studio-bokeh",
    name: "Gentle Bokeh",
    category: "Studio",
    description: "Abstract shallow depth-of-field bokeh with soft circular highlights.",
    previewColor: "from-emerald-950 via-teal-900 to-cyan-950",
    defaultClothingMode: "preserve",
    environment: "an abstract shallow depth-of-field bokeh background with soft circular highlights.",
    outfit: "",
    lighting: "unified, professional studio lighting (e.g., softbox) consistently across all subjects.",
    compositionHint: "",
  },

  // ── Themed Presets ────────────────────────────────────────────────────
  {
    id: "formal-classic",
    name: "Classic Studio Formal",
    category: "Formal",
    description: "Tailored dark suits and formal evening gowns against a timeless seamless studio backdrop.",
    badge: "Popular",
    previewColor: "from-slate-900 via-slate-800 to-zinc-900",
    defaultClothingMode: "restyle",
    environment: "A high-end professional photography studio with a subtle neutral dark gray seamless backdrop and soft falloff.",
    outfit: "Crisp black and navy blue formal suits with ties or bowties for male subjects, and elegant evening dresses or suits for female subjects. Coordinated formal attire.",
    lighting: "Classic 3-point studio strobe lighting with soft key light, gentle fill light, and subtle hair/rim light separation.",
    compositionHint: "Arranged naturally in a semi-circular studio pose, with taller adults slightly behind and centered subjects angled inwards.",
  },
  {
    id: "royal-palace",
    name: "European Royal",
    category: "Royal",
    description: "Opulent mahogany palace hall with velvet gowns, golden chandeliers, and oil-painting warmth.",
    badge: "Premium",
    previewColor: "from-amber-950 via-amber-900 to-yellow-950",
    defaultClothingMode: "restyle",
    environment: "An elegant European royal palace drawing room featuring carved mahogany wainscoting, gold leaf ornate framed portraits, and rich damask drapes.",
    outfit: "Aristocratic royal evening attire: deep royal blue, emerald green, or dark burgundy velvet suits, tailored waistcoats, and ornate silk ball gowns.",
    lighting: "Warm golden chandelier lighting complemented by soft directional window light, casting rich painterly highlights.",
    compositionHint: "Regal portrait arrangement with elders seated on carved velvet armchairs and remaining family members standing attentively behind.",
  },
  {
    id: "cozy-fireplace",
    name: "Cozy Living Room",
    category: "Cozy",
    description: "Warm cable-knit sweaters gathered around a glowing fireplace in a cozy timber home.",
    badge: "Trending",
    previewColor: "from-orange-950 via-amber-900 to-stone-900",
    defaultClothingMode: "restyle",
    environment: "A rustic modern timber living room with a brick fireplace emitting a gentle warm glow and plush beige sofa.",
    outfit: "Cozy autumn knitwear: cream, oatmeal, and terracotta cable-knit sweaters, dark denim jeans, and warm wool trousers.",
    lighting: "Warm ambient fireplace glow mixed with soft indoor incandescent lamps creating a cozy home atmosphere.",
    compositionHint: "Relaxed family huddle on and around a comfortable couch, leaning into each other with warm smiles.",
  },
  {
    id: "kitchen-baking",
    name: "Kitchen Baking",
    category: "Lifestyle",
    description: "Baking together at a sunlit marble kitchen island in matching linen aprons.",
    previewColor: "from-stone-700 via-stone-800 to-neutral-900",
    defaultClothingMode: "restyle",
    environment: "A bright, modern farmhouse kitchen with marble countertops, wooden rolling pins, flour dust, and fresh baked goods.",
    outfit: "Casual linen clothes, cozy aprons in neutral tones, relaxed home kitchen aesthetic.",
    lighting: "Abundant morning sunlight streaming through large kitchen windows, bright and airy.",
    compositionHint: "Gathered around the kitchen island counter, smiling and interacting naturally while holding baking tools.",
  },
  {
    id: "bed-jump",
    name: "Bed Jump Fun",
    category: "Lifestyle",
    description: "Playful morning energy jumping on a plush white bed in matching pajamas.",
    previewColor: "from-blue-950 via-indigo-900 to-slate-900",
    defaultClothingMode: "restyle",
    environment: "A spacious light-filled master bedroom with a large plush white duvet bed and soft pillows.",
    outfit: "color-coordinated cotton night wear sets as per the suitable gender.",
    lighting: "High-key bright morning sunshine diffusing through sheer white curtains.",
    compositionHint: "Dynamic mid-jump or joyful sitting as per best framing pose on the bed mattress with pillow fight energy and genuine laughter.",
  },
  {
    id: "autumn-park",
    name: "Autumn Park Walk",
    category: "Outdoor",
    description: "Golden hour foliage under oak trees with fall trench coats and plaid scarves.",
    badge: "Popular",
    previewColor: "from-amber-900 via-orange-950 to-stone-900",
    defaultClothingMode: "restyle",
    environment: "A breathtaking city park in peak autumn, surrounded by golden maple and oak trees with fallen orange leaves on the ground.",
    outfit: "Classic autumn trench coats, wool overcoats, muted mustard and forest green scarves, and leather boots, clothing must be gender-appropriate.",
    lighting: "Warm late-afternoon golden hour sunlight casting sun flares and soft rim lighting through tree branches.",
    compositionHint: "Walking arm-in-arm or standing together on a winding park path surrounded by golden foliage.",
  },
  {
    id: "beach-sunset",
    name: "Golden Beach Sunset",
    category: "Outdoor",
    description: "Linen outfits and ocean breeze against a glowing pink and gold coastal sky.",
    previewColor: "from-rose-950 via-orange-900 to-amber-950",
    defaultClothingMode: "restyle",
    environment: "A pristine sandy beach at sunset with gentle ocean waves and a vibrant golden-pink sky horizon.",
    outfit: "Lightweight white and beige linen shirts, breezy maxi dresses for women if present, barefoot sandy look, clothing must be gender-appropriate.",
    lighting: "Vibrant sunset glow with dramatic backlighting and soft warm fill on faces.",
    compositionHint: "Standing or sitting together on the sand with arms wrapped around each other, looking toward the horizon.",
  },
  {
    id: "wildflower-meadow",
    name: "Wildflower Meadow",
    category: "Outdoor",
    description: "A relaxed family portrait among soft meadow flowers in warm late-afternoon light.",
    previewColor: "from-amber-700 via-rose-700 to-emerald-900",
    defaultClothingMode: "restyle",
    environment: "A peaceful open meadow with scattered seasonal wildflowers and softly blurred greenery, keeping the foreground around every subject clean and unobstructed.",
    outfit: "Simple coordinated casual clothing in cream, tan, muted blue, and soft floral accents, with solid fabrics and natural textures.",
    lighting: "Warm late-afternoon sunlight with soft frontal fill so every face remains evenly exposed and clearly defined.",
    compositionHint: "A stable, close family grouping in one shallow arrangement, standing or seated naturally with every face oriented toward the camera and fully unobstructed.",
  },
  {
    id: "boho-meadow",
    name: "Boho Meadow",
    category: "Outdoor",
    description: "Earth-toned bohemian styling in a quiet sunlit grassland setting.",
    previewColor: "from-stone-700 via-amber-800 to-olive-950",
    defaultClothingMode: "restyle",
    environment: "A quiet open grassland with pale natural grasses, subtle distant trees, and an uncluttered softly blurred background.",
    outfit: "Coordinated bohemian-inspired clothing in rust, ivory, olive, and warm brown, using simple flowing fabrics without face-covering hats or oversized accessories.",
    lighting: "Soft diffused golden daylight with balanced exposure and gentle natural shadows consistently across all faces.",
    compositionHint: "A classic upright multi-generation portrait arrangement with subjects close together, relaxed shoulders, visible faces, and direct camera engagement.",
  },
  {
    id: "poolside-summer",
    name: "Poolside Summer",
    category: "Lifestyle",
    description: "Bright family poolside energy with clean water tones and natural summer smiles.",
    previewColor: "from-cyan-500 via-sky-700 to-teal-900",
    defaultClothingMode: "restyle",
    environment: "A clean private outdoor swimming pool with calm turquoise water, a simple stone edge, and softly blurred summer greenery behind the family.",
    outfit: "Tasteful coordinated family swimwear and lightweight summer cover-ups in navy, white, and muted aqua tones.",
    lighting: "Bright natural daylight softened with even frontal fill, controlling water reflections so faces and skin tones remain clear and consistent.",
    compositionHint: "A stable group seated or standing together at the pool edge, with gentle water movement kept below shoulder level and every face clearly visible toward the camera.",
  },
  {
    id: "winter-snow-day",
    name: "Winter Snow Day",
    category: "Holiday",
    description: "A cheerful snowy portrait beside a classic family-built snowman.",
    previewColor: "from-slate-300 via-blue-600 to-indigo-950",
    defaultClothingMode: "restyle",
    environment: "A quiet snow-covered park with soft evergreen trees in the distance and one simple snowman positioned beside, never between, the family members.",
    outfit: "Coordinated winter coats in navy, burgundy, plum, and warm neutrals, with scarves below the chin and hats kept above the eyebrows.",
    lighting: "Soft overcast winter daylight with gentle warm fill on faces, clean skin tones, and no heavy falling snow crossing facial features.",
    compositionHint: "The family stands closely together beside the snowman in a calm camera-facing pose, with clear separation between every face and no subject obscured by props.",
  },
  {
    id: "urban-street",
    name: "Urban Street",
    category: "Lifestyle",
    description: "Polished city style on a quiet street with softly blurred architecture.",
    previewColor: "from-zinc-700 via-stone-600 to-slate-900",
    defaultClothingMode: "restyle",
    environment: "A quiet wide city sidewalk framed by classic brick architecture, with distant urban details softly blurred and no background crowd near the subjects.",
    outfit: "Polished smart-casual gender-appropriate city clothing.",
    lighting: "Soft directional daylight with balanced frontal fill, consistent color temperature, and controlled building shadows across every subject.",
    compositionHint: "A stationary editorial family grouping on the sidewalk, arranged in a shallow line with natural closeness, visible full faces, and all subjects looking toward the camera.",
  },
  {
    id: "scenic-road-trip",
    name: "Scenic Road Trip",
    category: "Lifestyle",
    description: "A relaxed travel portrait beside a parked vintage car at a scenic overlook.",
    previewColor: "from-sky-700 via-orange-700 to-stone-900",
    defaultClothingMode: "restyle",
    environment: "A scenic open-road overlook with distant desert mountains and one parked vintage convertible positioned clearly behind the family.",
    outfit: "Relaxed coordinated gender-appropriate travel clothing, muted earth tones, and practical casual layers.",
    lighting: "Clear late-morning daylight with soft frontal fill and uniform exposure across all faces, avoiding harsh windshield reflections.",
    compositionHint: "The family stands together safely beside the parked car in a stable camera-facing group pose, with the vehicle serving only as a background element.",
  },
  {
    id: "rooftop-evening",
    name: "Rooftop Evening",
    category: "Lifestyle",
    description: "An intimate twilight gathering under warm string lights and a distant skyline.",
    previewColor: "from-violet-950 via-orange-900 to-slate-950",
    defaultClothingMode: "restyle",
    environment: "A private rooftop terrace at twilight with warm string lights overhead, a distant softly blurred city skyline, and a clean uncluttered setting around the family.",
    outfit: "Coordinated evening smart-casual clothing in navy, burgundy, charcoal, and warm cream with simple refined silhouettes.",
    lighting: "Warm string-light ambience balanced by soft professional frontal fill so every face remains sharp, naturally colored, and evenly illuminated.",
    compositionHint: "A close stationary family grouping around a simple rooftop table, with hands and faces unobstructed, no crowd extras, and everyone oriented toward the camera.",
  },
  {
    id: "christmas-magic",
    name: "Christmas Holiday",
    category: "Holiday",
    description: "Festive red & green holiday sweaters beside a towering decorated pine tree with fairy lights.",
    badge: "Seasonal",
    previewColor: "from-emerald-950 via-red-950 to-stone-900",
    defaultClothingMode: "restyle",
    environment: "A grand holiday living room featuring a tall, illuminated Christmas tree decorated with gold baubles, ribbon, and wrapped gifts.",
    outfit: "Festive holiday attire: red and dark green knit sweaters, tartan plaid shirts, or elegant holiday dress clothes.",
    lighting: "Sparkling bokeh from Christmas tree fairy lights combined with warm hearth illumination.",
    compositionHint: "Seated around the Christmas tree holding ornaments or hot cocoa cups, smiling together.",
  },
  {
    id: "black-white-fineart",
    name: "Fine Art Monochrome",
    category: "Fine Art",
    description: "Dramatic high-contrast black and white portrait photography with deep shadows.",
    previewColor: "from-black via-zinc-900 to-neutral-900",
    defaultClothingMode: "restyle",
    environment: "A pure deep matte black background with zero color distraction.",
    outfit: "Simple black turtlenecks, charcoal t-shirts, or solid dark clothing emphasizing facial expressions and eye contact.",
    lighting: "Chiaroscuro studio lighting with strong key light creating dramatic highlights and deep rich shadow contrast.",
    compositionHint: "Tight group composition focused on close proximity, touch, and expressive facial identity in monochrome.",
  },
  {
    id: "retro-80s",
    name: "Retro Vintage 80s",
    category: "Retro",
    description: "Vintage 1980s studio portrait aesthetic with soft laser background effects and classic denim.",
    previewColor: "from-purple-950 via-indigo-950 to-blue-950",
    defaultClothingMode: "restyle",
    environment: "A nostalgic 1980s portrait studio backdrop with subtle blue and magenta lighting vignettes or soft cloud texture.",
    outfit: "Retro 80s fashion: acid-wash denim jackets, double-breasted suits with shoulder pads, patterned knit sweaters.",
    lighting: "Vintage film camera lighting soft-focus sheen, subtle grain, and nostalgic color grading.",
    compositionHint: "Classic multi-tiered pose with stacked shoulders and proud 80s studio posture.",
  },
  {
    id: "vintage-oil-painting",
    name: "Vintage Oil Canvas",
    category: "Fine Art",
    description: "Classic Renaissance oil painting style with textured canvas brushwork and rich tones.",
    previewColor: "from-yellow-950 via-stone-900 to-amber-950",
    defaultClothingMode: "restyle",
    environment: "A textured oil canvas backdrop with mottled earthy brown and deep ochre tones.",
    outfit: "Timeless vintage attire, wool vests, linen blouses, classical tailored jackets.",
    lighting: "Rembrandt studio lighting with distinct triangular key light on cheeks and dramatic shadow depth.",
    compositionHint: "Classical triangular portrait structure reminiscent of 19th century painted family masterworks.",
  },
]

export function getThemeById(id: string): FamilyPortraitTheme {
  return FAMILY_PORTRAIT_THEMES.find((t) => t.id === id) || FAMILY_PORTRAIT_THEMES[0]
}
